# Generated by Django 3.0 on 2019-12-12 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20191212_1742'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Example',
        ),
    ]
